DROP TABLE IF EXISTS t;
CREATE TABLE t (a INTEGER, b INTEGER);
INSERT INTO t VALUES (1, 1);
INSERT INTO t VALUES (1, 2);
INSERT INTO t VALUES (1, 3);
INSERT INTO t VALUES (2, 4);
INSERT INTO t VALUES (2, 2);

SELECT a, b, first_value(b) OVER (PARTITION BY a) AS value FROM t;
